### ISSUE TITLE
Error: invalid wire type 7 at offset 427

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-MobileQQ-Andriod#11]
json:
<details>
QQ号已隐藏

```
    {
        "_id": 4850,
        "extInt": 0,
        "extLong": 0,
        "extStr": "{\"key_message_extra_info_flag\":\"0\"}",
        "extraflag": 0,
        "frienduin": "***",
        "isValid": 1,
        "isread": 1,
        "issend": 1,
        "istroop": 0,
        "longMsgCount": 1,
        "longMsgId": 15799,
        "longMsgIndex": 0,
        "msgData": {
            "type": "Buffer",
            "data": [
                58,
                67,
                21,
                67,
                68,
                85,
                66,
                81,
                93,
                85,
                31,
                95,
                93,
                69,
                86,
                81,
                68,
                85,
                86,
                21,
                0,
                31,
                123,
                94,
                84,
                72,
                95,
                89,
                94,
                31,
                84,
                91,
                68,
                81,
                31,
                81,
                85,
                93,
                30,
                78,
                85,
                94,
                89,
                85,
                94,
                78,
                30,
                93,
                85,
                82,
                89,
                92,
                87,
                75,
                65,
                31,
                110,
                85,
                94,
                89,
                85,
                94,
                78,
                31,
                125,
                85,
                82,
                89,
                92,
                87,
                107,
                97,
                31,
                89,
                88,
                81,
                78,
                64,
                89,
                89,
                31,
                83,
                82,
                81,
                68,
                89,
                95,
                93,
                31,
                85,
                92,
                8,
                31,
                121,
                81,
                83,
                82,
                85,
                111,
                15,
                0,
                8,
                8,
                3,
                11,
                1,
                4,
                8,
                7,
                2,
                92,
                6,
                85,
                92,
                8,
                32,
                213,
                136,
                49,
                40,
                51,
                26,
                48,
                26,
                13,
                31,
                1,
                9,
                0,
                0,
                9,
                3,
                1,
                2,
                4,
                2,
                29,
                3,
                14,
                0,
                0,
                10,
                6,
                7,
                8,
                8,
                2,
                23,
                6,
                2,
                127,
                1,
                3,
                0,
                6,
                121,
                9,
                113,
                127,
                118,
                3,
                127,
                9,
                118,
                15,
                7,
                8,
                121,
                7,
                116,
                116,
                5,
                8,
                0,
                116,
                3,
                1,
                113,
                123,
                4,
                2,
                26,
                6,
                2,
                127,
                1,
                3,
                0,
                6,
                121,
                9,
                113,
                127,
                118,
                3,
                127,
                9,
                118,
                15,
                7,
                8,
                121,
                7,
                116,
                116,
                5,
                8,
                0,
                116,
                3,
                1,
                113,
                123,
                4,
                10,
                58,
                114,
                178,
                59,
                31,
                67,
                68,
                93,
                72,
                81,
                87,
                95,
                31,
                85,
                87,
                69,
                92,
                91,
                68,
                85,
                94,
                31,
                0,
                31,
                115,
                84,
                84,
                66,
                85,
                89,
                84,
                21,
                84,
                81,
                78,
                81,
                31,
                89,
                95,
                93,
                30,
                70,
                95,
                94,
                83,
                95,
                94,
                68,
                20,
                93,
                95,
                88,
                89,
                92,
                95,
                65,
                65,
                31,
                102,
                95,
                94,
                83,
                95,
                94,
                68,
                21,
                125,
                95,
                88,
                89,
                92,
                95,
                97,
                97,
                31,
                70,
                82,
                69,
                93,
                88,
                31,
                111,
                23,
                1,
                9,
                8,
                2,
                9,
                13,
                8,
                4,
                5,
                11,
                101,
                115,
                81,
                89,
                88,
                85,
                101,
                5,
                0,
                2,
                8,
                1,
                11,
                1,
                4,
                2,
                5,
                8,
                86,
                6,
                95,
                86,
                8,
                101,
                1,
                6,
                8,
                0,
                5,
                14,
                0,
                0,
                5,
                2,
                10,
                0,
                0,
                20,
                90,
                64,
                93,
                122,
                48,
                104,
                48,
                104,
                58,
                80,
                58,
                90,
                249,
                59,
                56,
                247,
                202,
                170,
                235,
                168,
                226,
                238,
                241,
                80,
                34,
                48,
                1,
                4,
                2,
                7,
                13,
                4,
                5,
                3,
                8,
                6,
                34,
                48,
                18,
                13,
                31,
                1,
                14,
                2,
                5,
                7,
                6,
                15,
                9,
                8,
                12,
                29,
                2,
                12,
                2,
                7,
                15,
                6,
                9,
                2,
                3,
                4,
                29,
                4,
                8,
                117,
                1,
                9,
                0,
                4,
                121,
                9,
                113,
                127,
                118,
                3,
                127,
                9,
                118,
                5,
                5,
                2,
                115,
                7,
                126,
                116,
                7,
                8,
                0,
                116,
                3,
                1,
                113,
                123,
                4,
                26,
                70,
                29,
                73,
                68,
                95,
                72,
                81,
                87,
                95,
                31,
                85,
                87,
                69,
                92,
                91,
                68,
                85,
                84,
                29,
                10,
                31,
                113,
                84,
                84,
                66,
                85,
                89,
                84,
                21,
                84,
                81,
                78,
                81,
                31,
                83,
                93,
                87,
                30,
                68,
                95,
                94,
                83,
                95,
                94,
                68,
                20,
                93,
                95,
                88,
                89,
                92,
                85,
                67,
                75,
                31,
                100,
                95,
                94,
                83,
                95,
                94,
                68,
                21,
                125,
                95,
                88,
                89,
                92,
                85,
                99,
                107,
                31,
                83,
                82,
                81,
                68,
                74,
                89,
                83,
                21,
                83,
                88,
                91,
                68,
                68,
                88,
                71,
                87,
                82,
                31,
                91,
                9,
                8,
                21,
                115,
                81,
                89,
                88,
                85,
                101,
                4,
                8,
                7,
                83,
                92,
                4,
                8,
                91,
                84,
                5,
                95,
                3,
                9,
                91,
                9,
                8,
                101,
                88,
                84,
                0,
                50,
                66,
                53,
                176,
                59,
                48,
                184,
                59,
                48,
                162,
                59,
                22,
                111,
                101,
                86,
                86,
                81,
                5,
                2,
                86,
                7,
                12,
                29,
                0,
                94,
                0,
                8,
                23,
                4,
                2,
                2,
                81,
                29,
                81,
                2,
                11,
                81,
                29,
                89,
                9,
                8,
                9,
                86,
                4,
                91,
                2,
                7,
                2,
                2,
                81,
                168,
                51,
                197,
                207,
                207,
                197,
                207,
                207,
                197,
                207,
                207,
                59,
                144,
                49,
                197,
                207,
                207,
                207,
                205,
                197,
                207,
                207,
                197,
                49,
                152,
                59,
                48,
                128,
                59,
                195,
                50,
                130,
                49,
                195,
                50,
                242,
                59,
                208,
                51,
                242,
                49,
                208,
                57,
                224,
                49,
                210,
                55,
                232,
                59,
                48,
                208,
                49,
                50,
                210,
                49,
                48,
                202,
                49,
                48,
                194,
                49,
                48,
                184,
                50,
                48,
                170,
                50,
                48
            ]
        },
        "msgId": 0,
        "msgUid": "72057595365129007",
        "msgseq": 226246071,
        "msgtype": -2000,
        "selfuin": "***",
        "sendFailCode": 0,
        "senderuin": "***",
        "shmsgseq": 15799,
        "time": 1620540174,
        "uniseq": "6960167040912806574",
        "versionCode": 3,
        "vipBubbleID": 0
    }
```
</details>
error:

```
4847
4848
4849
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377
            throw Error("invalid wire type " + wireType + " at offset " + this.pos);
                  ^

Error: invalid wire type 7 at offset 427
    at Reader.skipType (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377:19)
    at Reader.skipType (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:368:22)
    at Type.ForwardExtra$decode [as decode] (eval at Codegen (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\@)
    at Type.PicRec$decode [as decode] (eval at Codegen (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\@protob)
    at ddProtoBuf (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\utils\ddData.js:20:46)
    at image (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\image\index.js:14:20)
    at typeMap (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeMap.js:93:36)
    at ToMsg (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\index.js:30:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\index.js:26:20

Node.js v18.17.0
```

还是原来的kc

**Comment by lqzhgood** [comment]
你这一条在QQ里面能显示吗？貌似数据有问题~

**Comment by hitech-h** [comment]
![IMG_20230726_103617](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/137307061/d3c8300e-a22d-4e6c-89d0-3f9b08362615)
在这个时间段里是有信息的
只有三条，但不知道是指哪一条

**Comment by lqzhgood** [comment]
这条消息的类型是 图片，应该是第三个图片~

**Comment by hitech-h** [comment]
图片应该被清理掉了，也不知道原文件是啥了

**Comment by lqzhgood** [comment]
增加 java 的解码方式，与 js 结合
https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/commit/bde0da52e31d82c99d1843b19d803a55e774045f
