### ISSUE TITLE
[Bug]解密时报错 TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-MobileQQ-Andriod#13]
关键数据
```
9651
9652
9653
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.parse (node:path:913:5)
    at audio (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\audio.js:51:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async typeMap (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeMap.js:101:30)
    at async ToMsg (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\index.js:30:44)
    at async D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\index.js:37:20 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.16.1
```

<details> 
    <summary>所指json</summary>

```
    {
        "_id": 9654,
        "extInt": 0,
        "extLong": 1,
        "extStr": "{\"vip_font_effect_id\":\"0\",\"vip_face_id\":\"0\",\"is_to_robot\":\"0\",\"wave_form\":\"[23,165,84,84,184,154,163,86,15,7,131,83,80,114,131,141,241,125,101,120,30,121,87,117,207,138,113,83,162,9,5,78,195,176,51,167,134,170,107,99,70,19,88,127,80,121,149,124,49,206,159,161,142,64,9,10,6,191,21,6,118,140,22,212,191,33,114,221,94,245,249,230,120,151,104,81,9,12,17,68,5,4,182,255,73,207,192,222,211,114,9,199,113,182,209,240,208,199,166,0]\"}",
        "extraflag": 0,
        "frienduin": "***",
        "isValid": 1,
        "isread": 1,
        "issend": 0,
        "istroop": 0,
        "longMsgCount": 0,
        "longMsgId": 0,
        "longMsgIndex": 0,
        "msgData": {
            "type": "Buffer",
            "data": [
                58,
                22,
                11,
                8,
                90,
                117,
                121,
                83,
                110,
                115,
                66,
                10,
                5,
                81,
                80,
                65,
                68,
                87,
                2,
                126,
                7,
                99,
                101,
                98,
                7,
                13,
                1,
                83,
                82,
                118,
                101,
                115,
                96,
                1,
                111,
                71,
                82,
                123,
                32,
                58,
                40,
                50,
                26,
                48,
                26,
                30,
                1,
                8,
                80,
                127,
                121,
                83,
                102,
                121,
                66,
                0,
                15,
                81,
                90,
                75,
                68,
                87,
                10,
                116,
                7,
                105,
                111,
                98,
                7,
                5,
                11,
                83,
                88,
                124,
                101,
                121,
                106,
                1,
                111,
                79,
                88,
                123,
                8,
                16,
                4,
                1,
                113,
                10,
                7,
                9,
                126,
                8,
                7,
                124,
                7,
                116,
                11,
                115,
                0,
                11,
                1,
                3,
                113,
                7,
                9,
                8,
                3,
                120,
                0,
                7,
                120,
                118,
                1,
                13,
                114,
                9,
                0,
                57,
                64,
                68,
                70,
                89,
                85,
                94,
                78,
                85,
                66,
                122,
                53,
                120,
                58,
                96,
                49,
                98,
                48,
                82,
                48,
                90,
                58,
                64,
                49,
                186,
                49,
                227,
                212,
                195,
                187,
                60,
                184,
                49,
                245,
                242,
                213,
                187,
                52,
                170,
                49,
                49,
                162,
                49,
                19,
                154,
                49,
                48,
                144,
                49,
                48,
                138,
                49,
                48,
                138,
                51,
                85,
                31,
                67,
                78,
                95,
                66,
                91,
                87,
                85,
                21,
                85,
                93,
                79,
                92,
                81,
                68,
                87,
                94,
                31,
                0,
                21,
                113,
                94,
                94,
                66,
                95,
                83,
                84,
                31,
                94,
                81,
                68,
                81,
                29,
                89,
                95,
                93,
                20,
                68,
                85,
                84,
                83,
                85,
                84,
                68,
                30,
                87,
                95,
                82,
                89,
                94,
                95,
                65,
                65,
                21,
                100,
                85,
                84,
                83,
                85,
                84,
                68,
                31,
                119,
                95,
                82,
                89,
                94,
                95,
                97,
                97,
                21,
                1,
                3,
                10,
                0,
                3,
                9,
                1,
                8,
                14,
                2,
                31,
                64,
                70,
                78,
                31,
                83,
                8,
                83,
                111,
                8,
                0,
                2,
                8,
                0,
                8,
                11,
                2,
                1,
                1,
                0,
                13,
                3,
                3,
                3,
                8,
                5,
                20,
                67,
                92,
                81,
                240,
                49,
                58,
                248,
                49,
                48,
                226,
                59,
                48
            ]
        },
        "msgId": 0,
        "msgUid": "72057595923480401",
        "msgseq": 1635344719,
        "msgtype": -2002,
        "selfuin": "***",
        "sendFailCode": 0,
        "senderuin": "***",
        "shmsgseq": -16451,
        "time": 1635344719,
        "uniseq": "7024761455255391995",
        "versionCode": 3,
        "vipBubbleID": 0
    },
```
</details>
还是原来的kc

<details> 
    <summary>定位json过程</summary>

修改`tools\findOne.js`中`n=9653`并执行`node .\tools\findOne.js`
在`dist\_temp\table\message.json`寻找对应时间轴json
</details>

**Comment by lqzhgood** [comment]
https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/commit/9ebc46f0fe502be7d80c39ff4e81a9827a7f2c6a 已修复 没匹配到本地音频文件时不处理

更新`decode\typeHandle\audio.js`这一个文件即可
