### ISSUE TITLE
[Bug]解密时报错“TypeError: Cannot read properties of undefined (reading 'length')”

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-MobileQQ-Andriod#14]
其实上次解密时就有出现，忘记上传了
报错信息
```
0
1
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\addFriend.js:23
    for (let i = 0; i < o.field_nicepics.length; i++) {
                                         ^

TypeError: Cannot read properties of undefined (reading 'length')
    at handler (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\addFriend.js:23:42)
    at typeMap (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeMap.js:210:36)
    at ToMsg (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\index.js:30:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\index.js:50:20

Node.js v18.16.1
```

<details>
<summary>json</summary>

```
[
    {
        "_id": 3,
        "extInt": 0,
        "extLong": 0,
        "extStr": "",
        "extraflag": 0,
        "frienduin": "***",
        "isValid": 1,
        "isread": 1,
        "issend": 0,
        "istroop": 0,
        "longMsgCount": 0,
        "longMsgId": 0,
        "longMsgIndex": 0,
        "msgData": {
            "type": "Buffer",
            "data": [
                75,
                16,
                92,
                89,
                85,
                86,
                84,
                111,
                88,
                81,
                67,
                95,
                64,
                66,
                85,
                86,
                89,
                92,
                87,
                24,
                10,
                75,
                24,
                81,
                87,
                95,
                18,
                10,
                11,
                0,
                2,
                22,
                18,
                87,
                85,
                92,
                94,
                85,
                66,
                24,
                10,
                2,
                22,
                18,
                64,
                86,
                81,
                83,
                95,
                18,
                10,
                18,
                215,
                131,
                143,
                213,
                141,
                174,
                18,
                22,
                18,
                81,
                94,
                84,
                86,
                72,
                84,
                111,
                67,
                64,
                89,
                18,
                10,
                24,
                213,
                136,
                170,
                213,
                191,
                141,
                214,
                175,
                159,
                214,
                185,
                142,
                16,
                71,
                28,
                18,
                92,
                89,
                85,
                86,
                84,
                111,
                74,
                85,
                66,
                73,
                95,
                94,
                81,
                94,
                101,
                92,
                81,
                88,
                85,
                92,
                73,
                18,
                10,
                97,
                18,
                1,
                222,
                136,
                154,
                213,
                183,
                139,
                213,
                160,
                182,
                213,
                149,
                135,
                213,
                191,
                177,
                18,
                28,
                24,
                215,
                187,
                158,
                215,
                151,
                160,
                213,
                128,
                151,
                18,
                22,
                18,
                212,
                128,
                188,
                214,
                150,
                145,
                213,
                181,
                177,
                24,
                28,
                18,
                220,
                168,
                190,
                220,
                167,
                149,
                220,
                166,
                137,
                210,
                184,
                175,
                18,
                30,
                24,
                213,
                184,
                186,
                213,
                158,
                152,
                213,
                145,
                174,
                18,
                109,
                22,
                18,
                86,
                89,
                87,
                86,
                84,
                111,
                75,
                74,
                95,
                84,
                85,
                18,
                0,
                75,
                18,
                83,
                93,
                87,
                111,
                71,
                72,
                92,
                67,
                24,
                10,
                107,
                24,
                88,
                68,
                78,
                64,
                10,
                102,
                31,
                108,
                31,
                83,
                11,
                30,
                65,
                74,
                89,
                83,
                20,
                83,
                94,
                102,
                31,
                64,
                73,
                83,
                15,
                108,
                29,
                108,
                1,
                1,
                108,
                115,
                6,
                115,
                119,
                0,
                116,
                88,
                119,
                12,
                101,
                108,
                31,
                80,
                75,
                97,
                86,
                108,
                74,
                5,
                67,
                66,
                66,
                125,
                105,
                99,
                98,
                125,
                70,
                123,
                64,
                20,
                83,
                65,
                94,
                66,
                1,
                105,
                113,
                7,
                125,
                94,
                102,
                114,
                7,
                105,
                121,
                118,
                84,
                100,
                113,
                10,
                71,
                82,
                106,
                93,
                65,
                123,
                93,
                2,
                13,
                95,
                69,
                72,
                86,
                113,
                104,
                122,
                108,
                95,
                98,
                125,
                126,
                117,
                125,
                104,
                5,
                126,
                96,
                126,
                6,
                103,
                10,
                124,
                69,
                13,
                84,
                98,
                111,
                95,
                122,
                15,
                1,
                98,
                104,
                97,
                30,
                97,
                104,
                86,
                103,
                117,
                105,
                86,
                1,
                120,
                99,
                120,
                126,
                101,
                123,
                96,
                105,
                66,
                117,
                102,
                87,
                97,
                125,
                73,
                17,
                108,
                21,
                83,
                22,
                95,
                91,
                13,
                11,
                22,
                91,
                64,
                15,
                11,
                22,
                64,
                78,
                13,
                0,
                28,
                82,
                95,
                7,
                26,
                97,
                108,
                68,
                114,
                96,
                2,
                124,
                82,
                97,
                107,
                98,
                117,
                121,
                83,
                17,
                28,
                68,
                92,
                7,
                1,
                22,
                67,
                71,
                7,
                0,
                2,
                11,
                6,
                5,
                10,
                2,
                0,
                3,
                8,
                22,
                78,
                93,
                13,
                1,
                4,
                9,
                0,
                0,
                12,
                2,
                0,
                10,
                0,
                22,
                73,
                83,
                85,
                7,
                5,
                2,
                29,
                3,
                11,
                29,
                2,
                28,
                66,
                86,
                7,
                4,
                29,
                10,
                18,
                28,
                24,
                88,
                68,
                68,
                66,
                0,
                108,
                31,
                102,
                31,
                81,
                11,
                30,
                65,
                74,
                89,
                83,
                20,
                83,
                94,
                108,
                29,
                74,
                67,
                83,
                5,
                108,
                31,
                108,
                1,
                1,
                108,
                115,
                6,
                115,
                119,
                0,
                126,
                90,
                125,
                6,
                101,
                102,
                31,
                82,
                75,
                97,
                86,
                108,
                74,
                5,
                67,
                66,
                66,
                119,
                107,
                105,
                104,
                125,
                76,
                123,
                66,
                20,
                83,
                65,
                104,
                72,
                90,
                11,
                125,
                3,
                2,
                116,
                95,
                30,
                69,
                15,
                67,
                1,
                118,
                2,
                82,
                82,
                69,
                93,
                75,
                89,
                5,
                82,
                3,
                95,
                126,
                121,
                114,
                106,
                100,
                93,
                97,
                95,
                85,
                127,
                115,
                74,
                85,
                81,
                88,
                126,
                12,
                123,
                81,
                84,
                4,
                66,
                8,
                73,
                87,
                118,
                8,
                3,
                115,
                115,
                100,
                126,
                86,
                93,
                124,
                91,
                106,
                87,
                100,
                74,
                5,
                95,
                13,
                67,
                3,
                20,
                4,
                103,
                120,
                65,
                73,
                82,
                98,
                95,
                123,
                0,
                124,
                30,
                8,
                127,
                17,
                108,
                21,
                83,
                22,
                85,
                89,
                7,
                1,
                22,
                81,
                64,
                13,
                11,
                22,
                64,
                78,
                13,
                0,
                28,
                82,
                95,
                13,
                24,
                107,
                103,
                113,
                120,
                96,
                0,
                124,
                87,
                113,
                107,
                98,
                117,
                121,
                83,
                17,
                22,
                70,
                86,
                13,
                1,
                28,
                67,
                69,
                7,
                0,
                1,
                9,
                2,
                0,
                12,
                5,
                2,
                9,
                10,
                28,
                68,
                93,
                7,
                1,
                6,
                9,
                0,
                0,
                12,
                2,
                0,
                10,
                0,
                22,
                67,
                81,
                95,
                13,
                5,
                8,
                29,
                1,
                11,
                29,
                2,
                28,
                66,
                86,
                7,
                4,
                29,
                0,
                16,
                22,
                18,
                88,
                78,
                68,
                64,
                0,
                108,
                31,
                102,
                31,
                81,
                11,
                30,
                65,
                64,
                91,
                89,
                30,
                83,
                84,
                108,
                31,
                74,
                67,
                83,
                5,
                108,
                31,
                108,
                1,
                1,
                102,
                113,
                12,
                121,
                119,
                10,
                126,
                88,
                125,
                6,
                101,
                102,
                31,
                82,
                75,
                97,
                86,
                102,
                72,
                15,
                73,
                66,
                72,
                119,
                105,
                105,
                104,
                125,
                76,
                123,
                66,
                20,
                83,
                65,
                105,
                122,
                14,
                125,
                71,
                14,
                65,
                100,
                88,
                6,
                125,
                20,
                103,
                7,
                20,
                102,
                93,
                81,
                99,
                91,
                125,
                113,
                75,
                81,
                26,
                9,
                9,
                74,
                111,
                87,
                95,
                120,
                83,
                71,
                121,
                64,
                127,
                71,
                103,
                108,
                100,
                5,
                79,
                67,
                71,
                118,
                121,
                91,
                104,
                93,
                122,
                74,
                94,
                83,
                6,
                8,
                74,
                101,
                104,
                79,
                96,
                9,
                13,
                2,
                9,
                92,
                7,
                6,
                70,
                71,
                76,
                7,
                73,
                11,
                66,
                3,
                82,
                7,
                85,
                117,
                87,
                120,
                79,
                98,
                30,
                71,
                19,
                102,
                31,
                83,
                28,
                85,
                91,
                7,
                1,
                22,
                81,
                64,
                13,
                11,
                22,
                64,
                68,
                15,
                10,
                22,
                82,
                85,
                13,
                84,
                93,
                125,
                83,
                123,
                3,
                105,
                126,
                120,
                113,
                125,
                96,
                127,
                115,
                83,
                27,
                22,
                68,
                86,
                13,
                1,
                28,
                67,
                69,
                7,
                0,
                2,
                1,
                7,
                10,
                1,
                9,
                14,
                22,
                68,
                87,
                13,
                1,
                12,
                3,
                0,
                10,
                6,
                2,
                0,
                2,
                10,
                22,
                67,
                89,
                85,
                13,
                15,
                2,
                29,
                11,
                1,
                29,
                8,
                22,
                66,
                86,
                15,
                14,
                29,
                0,
                24,
                28,
                18,
                82,
                68,
                68,
                74,
                10,
                108,
                21,
                108,
                31,
                81,
                3,
                20,
                65,
                64,
                83,
                83,
                30,
                89,
                94,
                108,
                21,
                64,
                67,
                89,
                15,
                108,
                31,
                100,
                11,
                1,
                102,
                121,
                6,
                121,
                125,
                0,
                126,
                82,
                119,
                6,
                111,
                108,
                31,
                82,
                67,
                107,
                86,
                102,
                64,
                5,
                73,
                72,
                66,
                119,
                99,
                99,
                104,
                119,
                70,
                123,
                66,
                28,
                89,
                65,
                83,
                93,
                100,
                114,
                83,
                68,
                68,
                12,
                30,
                30,
                105,
                87,
                118,
                69,
                83,
                124,
                83,
                0,
                88,
                98,
                89,
                64,
                87,
                123,
                84,
                105,
                96,
                10,
                122,
                122,
                100,
                125,
                16,
                2,
                97,
                124,
                102,
                90,
                16,
                117,
                6,
                73,
                6,
                68,
                89,
                83,
                127,
                5,
                64,
                76,
                86,
                26,
                13,
                0,
                64,
                15,
                91,
                87,
                83,
                87,
                117,
                76,
                6,
                126,
                92,
                81,
                124,
                125,
                8,
                72,
                106,
                95,
                118,
                119,
                73,
                95,
                124,
                73,
                105,
                92,
                113,
                119,
                24,
                88,
                70,
                97,
                27,
                108,
                31,
                89,
                22,
                85,
                81,
                13,
                1,
                28,
                91,
                64,
                13,
                3,
                28,
                64,
                68,
                7,
                0,
                22,
                88,
                95,
                13,
                112,
                71,
                83,
                113,
                114,
                115,
                83,
                122,
                121,
                87,
                97,
                104,
                117,
                115,
                89,
                17,
                22,
                78,
                92,
                13,
                11,
                22,
                67,
                69,
                15,
                10,
                2,
                0,
                15,
                7,
                7,
                14,
                5,
                3,
                10,
                22,
                68,
                87,
                13,
                1,
                6,
                1,
                10,
                0,
                6,
                8,
                0,
                0,
                10,
                22,
                67,
                89,
                85,
                13,
                15,
                2,
                29,
                1,
                3,
                23,
                2,
                22,
                72,
                86,
                13,
                14,
                29,
                0,
                24,
                28,
                18,
                82,
                68,
                68,
                64,
                8,
                102,
                31,
                108,
                21,
                81,
                1,
                20,
                65,
                64,
                83,
                83,
                30,
                89,
                94,
                108,
                31,
                66,
                73,
                83,
                15,
                102,
                31,
                102,
                11,
                1,
                102,
                121,
                6,
                121,
                125,
                0,
                126,
                88,
                117,
                12,
                101,
                108,
                21,
                82,
                65,
                107,
                86,
                102,
                64,
                5,
                73,
                72,
                66,
                119,
                105,
                97,
                98,
                125,
                70,
                113,
                66,
                30,
                89,
                65,
                84,
                114,
                6,
                86,
                81,
                83,
                4,
                85,
                69,
                116,
                113,
                101,
                111,
                91,
                105,
                126,
                30,
                7,
                10,
                114,
                67,
                120,
                116,
                71,
                1,
                72,
                77,
                72,
                4,
                96,
                64,
                114,
                88,
                92,
                91,
                110,
                82,
                123,
                124,
                93,
                118,
                68,
                67,
                77,
                85,
                5,
                9,
                0,
                101,
                98,
                124,
                125,
                14,
                6,
                105,
                86,
                2,
                86,
                113,
                10,
                76,
                116,
                68,
                117,
                3,
                119,
                109,
                81,
                117,
                16,
                88,
                118,
                106,
                125,
                122,
                121,
                83,
                72,
                92,
                4,
                73,
                0,
                84,
                113,
                105,
                87,
                27,
                108,
                31,
                89,
                22,
                85,
                91,
                15,
                11,
                22,
                91,
                74,
                13,
                1,
                28,
                64,
                68,
                7,
                0,
                22,
                88,
                95,
                13,
                127,
                115,
                123,
                70,
                113,
                126,
                87,
                113,
                118,
                71,
                113,
                104,
                117,
                115,
                89,
                17,
                22,
                68,
                94,
                7,
                1,
                22,
                73,
                69,
                13,
                10,
                2,
                5,
                9,
                5,
                5,
                8,
                5,
                1,
                4,
                20,
                78,
                93,
                13,
                11,
                6,
                3,
                10,
                0,
                6,
                8,
                0,
                0,
                10,
                22,
                67,
                83,
                87,
                7,
                5,
                2,
                23,
                1,
                1,
                23,
                2,
                22,
                72,
                86,
                13,
                14,
                29,
                0,
                18,
                111,
                71,
                77
            ]
        },
        "msgId": 0,
        "msgUid": 0,
        "msgseq": 1630060390,
        "msgtype": -7012,
        "selfuin": "***",
        "sendFailCode": 0,
        "senderuin": "***",
        "shmsgseq": 0,
        "time": 1630060390,
        "uniseq": "7001063255601843169",
        "versionCode": 3,
        "vipBubbleID": 0,
        "mExJsonObject": null
    }
]
```
</details>

**Comment by lqzhgood** [comment]
你能帮我看下添加的这个好友的资料中，性别是 **男** 还是 **女**  还是 其他什么吗？
因为解密出来的数据 gender 是个常量 2

`field_baseprofile: { age: 102, gender: 2, place: '广州', addfrd_src: '帐号查找' }`

**Comment by lqzhgood** [comment]
再来一张截图吧，不知道这条消息长啥样

**Comment by hitech-h** [comment]
已发至邮箱
