### ISSUE TITLE
exportTable 导出异常

### ISSUE THREAD

**Issue by lqzhgood** [lqzhgood/Shmily-Get-MobileQQ-Andriod#18]
```
PS D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod> npm run exportTable

> QQ-Mobile-Andriod-Export@1.0.0 exportTable
> node ./tools/exportTable.js


D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\database.js:63
                [util.cppdb]: { value: new addon.Database(filename, filenameGiven, anonymous, readonly, fileMustExist, timeout, verbose || null, buffer || null) },
                                       ^
SqliteError: unable to open database file
    at new Database (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\database.js:63:26)
    at conn (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:14:16)
    at Object.<anonymous> (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:28:16)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\tools\exportTable.js:3:25) {
  code: 'SQLITE_CANTOPEN'
}

Node.js v18.14.0
```
或者 
```
D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\database.js:59
                throw new TypeError('Cannot open database because the directory does not exist');
                ^

TypeError: Cannot open database because the directory does not exist
    at new Database (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\database.js:59:9)
    at conn (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:14:16)
    at Object.<anonymous> (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:28:16)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\tools\exportTable.js:3:25)

Node.js v18.14.0
```

**Comment by lqzhgood** [comment]
由 appinn.com F124nk1e 提供

解决方法：文件处于只读属性，改为可读可写。

**Comment by ww21x** [comment]
我也遇到了这个问题，提示文件不能打开。但我已经修改了文件的属性并将权限改为所有人都可修改。请问还有什么建议么

**Comment by lqzhgood** [comment]
> Cannot open database because the directory does not exist

`unable to open database file` 权限/文件是否损坏

 `Cannot open database because the directory does not exist` 是否放错位置
