### ISSUE TITLE
Config leftNum 填写错误

### ISSUE THREAD

**Issue by lqzhgood** [lqzhgood/Shmily-Get-MobileQQ-Andriod#19]
```
 D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod> npm run exportTable

> QQ-Mobile-Andriod-Export@1.0.0 exportTable
> node ./tools/exportTable.js


D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\methods\wrappers.js:5
        return this[cppdb].prepare(sql, this, false);
                           ^
SqliteError: no such table: mr_friend_XXXX_New
    at Database.prepare (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
    at D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:19:28
    at new Promise (<anonymous>)
    at db.jsonPromise (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:18:16)
    at message (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\decode\table\message.js:11:35)
    at exportTable (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:34:24)
    at D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\tools\exportTable.js:11:11
    at Object.<anonymous> (D:\transfer_redmi\AndroidQQ_MIUI\Shmily-Get-MobileQQ-Andriod\tools\exportTable.js:17:3)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10) {
  code: 'SQLITE_ERROR'
}

Node.js v18.14.0
```

**Comment by lqzhgood** [comment]
由 appinn.com F124nk1e 提供

请检查 Config 中的 QQ 号是否正确
// `friends.json` 为数据库中所有 QQ 号码
