### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'Shmily-Get-MobileQQ-Andriod\input\assets\chatpic\chatraw'

### ISSUE THREAD

**Issue by GreenHatHG** [lqzhgood/Shmily-Get-MobileQQ-Andriod#21]
麻烦再看下这个问题
```
PS D:\github\Shmily-Get-MobileQQ-Andriod> npm run md5assets

> QQ-Mobile-Andriod-Export@1.0.0 md5assets
> node ./tools/assetsFileMd5.js

node:fs:1525
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'D:\github\Shmily-Get-MobileQQ-Andriod\input\assets\chatpic\chatraw'
    at Object.readdirSync (node:fs:1525:3)
    at getDirMD5 (D:\github\Shmily-Get-MobileQQ-Andriod\utils\file.js:53:22)
    at makeAssetsImgDirMd5 (D:\github\Shmily-Get-MobileQQ-Andriod\decode\typeHandle\image\pre.js:13:27)
    at D:\github\Shmily-Get-MobileQQ-Andriod\tools\assetsFileMd5.js:12:11
    at Object.<anonymous> (D:\github\Shmily-Get-MobileQQ-Andriod\tools\assetsFileMd5.js:21:3)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'D:\\github\\Shmily-Get-MobileQQ-Andriod\\input\\assets\\chatpic\\chatraw'
}

Node.js v18.19.0
```
![image](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/34258355/d90593c1-da62-40fd-8d97-0f136055ee7e)

**Comment by lqzhgood** [comment]
看日期应该是安装时间比较短,  
数据较少, 有一些文件夹还没有~


![image](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/9134671/795ab8ab-32a5-495d-b7bc-e78072da95c0)
