### ISSUE TITLE
导出qq群聊信息

### ISSUE THREAD

**Issue by GreenHatHG** [lqzhgood/Shmily-Get-MobileQQ-Andriod#22]
请问下这个工具能导出qq群聊信息吗，我在config.js设置了leftNum为qq群号，但是导出时候却失败了

```
D:\github\Shmily-Get-MobileQQ-Andriod>npm run exportTable

> QQ-Mobile-Andriod-Export@1.0.0 exportTable
> node ./tools/exportTable.js


D:\github\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\methods\wrappers.js:5
        return this[cppdb].prepare(sql, this, false);
                           ^
SqliteError: no such table: mr_friend_C28879AB0FC65B8BF03A9E8A8945C7C3_New
    at Database.prepare (D:\github\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
    at D:\github\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:19:28
    at new Promise (<anonymous>)
    at db.jsonPromise (D:\github\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:18:16)
    at message (D:\github\Shmily-Get-MobileQQ-Andriod\decode\table\message.js:11:35)
    at exportTable (D:\github\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:34:24)
    at D:\github\Shmily-Get-MobileQQ-Andriod\tools\exportTable.js:15:11
    at Object.<anonymous> (D:\github\Shmily-Get-MobileQQ-Andriod\tools\exportTable.js:21:3)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10) {
  code: 'SQLITE_ERROR'
}

Node.js v18.19.0
```

如果不支持的话，有计划支持吗

**Comment by lqzhgood** [comment]
不支持~  群聊是另一个表, 那个表的数据未引入.

我的群里全是吹水, 导出来没啥意思  暂无计划~  

不过应该没啥难度, 复用单聊的逻辑应该是一样的,  但是估计有一些群聊特有的消息类型需要处理.  
看看谁有兴趣 PR 吧~
