### ISSUE TITLE
Error: Cannot find module './app/multimsg/index.js'

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-MobileQQ-Andriod#7]
源码下载时间：**7/22,21:54**

```
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>cnpm install
√ Installed 14 packages on D:\Shmily\Shmily-Get-MobileQQ-Andriod-main
√ All packages installed (used 22ms(network 19ms), speed 0B/s, json 0(0B), tarball 0B, manifests cache hit 0, etag hit 0 / miss 0)

D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>yarn install
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 14.40s.

D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run exportTable

> QQ-Mobile-Andriod-Export@1.0.0 exportTable
> node ./tools/exportTable.js


D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run md5assets

> QQ-Mobile-Andriod-Export@1.0.0 md5assets
> node ./tools/assetsFileMd5.js

ok 2293

D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run build

> QQ-Mobile-Andriod-Export@1.0.0 build
> cross-env NODE_ENV=production node index.js

node:internal/modules/cjs/loader:1077
  const err = new Error(message);
              ^

Error: Cannot find module './app/multimsg/index.js'
Require stack:
- D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\share5008\index.js
- D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeMap.js
- D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\index.js
- D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._resolveFilename (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\module-alias\index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\share5008\index.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Shmily\\Shmily-Get-MobileQQ-Andriod-main\\decode\\typeHandle\\share5008\\index.js',
    'D:\\Shmily\\Shmily-Get-MobileQQ-Andriod-main\\decode\\typeMap.js',
    'D:\\Shmily\\Shmily-Get-MobileQQ-Andriod-main\\decode\\index.js',
    'D:\\Shmily\\Shmily-Get-MobileQQ-Andriod-main\\index.js'
  ]
}

Node.js v18.16.1
```
因为npm install无法正常使用，故使用cnpm和yarn进行模块安装
多次安装也是这样，麻烦大佬了~

**Comment by lqzhgood** [comment]
这个是还没写完的 聊天记录 模块~
不小心传上去了~
你等我写完再更新一下代码吧~

**Comment by hitech-h** [comment]
突然想起，好像是忘记解压`decode\decryption\javaSerialization\emoticon2007\jdk-18.0.2.1.zip`了
话说昨天下午`Jul 23, 2023`代码是已经更新好了吗？想再尝试一下

**Comment by lqzhgood** [comment]
5008 的聊天记录好了~
2011的聊天记录还没~ https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/issues/8

[Shmily-Show](https://github.com/lqzhgood/Shmily-Show) 那边的代码也要更新~

**Comment by lqzhgood** [comment]
完成
