### ISSUE TITLE
Error: invalid wire type 7 at offset 427（且难以找出报错的json项）

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-MobileQQ-Andriod#9]
源码下载时间：2023/7/25 10:42
操作过程：
<details>

（因为我的信息数据，时间跨度太大，内容过多，为了减少工作量，我打算遇到报错的先把`"message.json"`内有关的项删除，之后再慢慢提交至Issues）
（下面用省略号省略部分代码）
已安装模块

  ```
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run exportTable

> QQ-Mobile-Andriod-Export@1.0.0 exportTable
> node ./tools/exportTable.js


D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run md5assets

> QQ-Mobile-Andriod-Export@1.0.0 md5assets
> node ./tools/assetsFileMd5.js

ok 3076

D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run build
> QQ-Mobile-Andriod-Export@1.0.0 build
> cross-env NODE_ENV=production node index.js

progress [----------------------------------------] 0% | ETA: 156s | 133/24705
……
❌ mixMsg unknown type {
……   
 "msgUid": "72057595309105552",
……
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\utils\index.js:48
        throw new Error(...v);
              ^

Error: mixMsg unknown type
    at Log.errAndThrow (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\utils\index.js:48:15)
    at mixMsg (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\mixMsg.js:60:21)
    at typeMap (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeMap.js:70:42)
    at ToMsg (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\index.js:29:50)
    at async D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\index.js:26:20

Node.js v18.16.1
  ```
看到这个报错，我打开`"message.json"`查找 `"msgUid": "72057595309105552"`，将这一项json删掉
再在网上搜索了一下原理，修改了`"index.js"`，删除了有关`npm run exportTable`和`npm run md5assets`的代码

```
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run build
> QQ-Mobile-Andriod-Export@1.0.0 build
> cross-env NODE_ENV=production node index.js
……
progress [========--------------------------------] 19% | ETA: 345s | 4811/24700D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377
            throw Error("invalid wire type " + wireType + " at offset " + this.pos);
                  ^

Error: invalid wire type 7 at offset 427
    at Reader.skipType (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377:19)
    at Reader.skipType (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:368:22)
    at Type.ForwardExtra$decode [as decode] (eval at Codegen (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:29:5)
    at Type.PicRec$decode [as decode] (eval at Codegen (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:47:26)
    at ddProtoBuf (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\utils\ddData.js:20:46)
    at image (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\image\index.js:14:20)
    at typeMap (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeMap.js:91:36)
    at ToMsg (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\index.js:29:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\index.js:15:20

Node.js v18.16.1
```
又找到`"message.json"`查找“第4812项，想着把它删掉可以继续运行
后面发现不行
于是又多运行几次

```
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run build
……
progress [========--------------------------------] 19% | ETA: 243s | 4819/24700D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377
            throw Error("invalid wire type " + wireType + " at offset " + this.pos);
                  ^
```

```
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run build
……
progress [========--------------------------------] 19% | ETA: 243s | 4833/24700D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377
            throw Error("invalid wire type " + wireType + " at offset " + this.pos);
                  ^
```
发现报错的项并不是“第4812项”，报错前的数值会不断变化，无法定位至准确项。推测原因是，解码时进度条大约每半秒才更新一次
（上面`Error: mixMsg unknown type`我之后再上传到Issues）

</details>
关键信息

```
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main>npm run build
> QQ-Mobile-Andriod-Export@1.0.0 build
> cross-env NODE_ENV=production node index.js
……
progress [========--------------------------------] 19% | ETA: 345s | 4811/24700D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377
            throw Error("invalid wire type " + wireType + " at offset " + this.pos);
                  ^

Error: invalid wire type 7 at offset 427
    at Reader.skipType (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377:19)
    at Reader.skipType (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:368:22)
    at Type.ForwardExtra$decode [as decode] (eval at Codegen (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:29:5)
    at Type.PicRec$decode [as decode] (eval at Codegen (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:47:26)
    at ddProtoBuf (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\utils\ddData.js:20:46)
    at image (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\image\index.js:14:20)
    at typeMap (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\typeMap.js:91:36)
    at ToMsg (D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\decode\index.js:29:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\index.js:15:20

Node.js v18.16.1
```
无法查找对应的`"message.json"`的项，因为解码时进度条大约每半秒才更新一次。报错前显示的数值会不断变化，无法定位至准确项。可以查看上面详情。

**Comment by lqzhgood** [comment]
```
progress [========--------------------------------] 19% | ETA: 345s | 4811/24700 
```
这条的进度是 4811

```bash
可以修改   .\tools\findOne.js 中的 n = 4811
执行 node .\tools\findOne.js 获取这条消息
```

进度条是处理一条更新一条

**Comment by lqzhgood** [comment]
如果你要跳过消息，可以修改这一行
https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/blob/12ea3baaf47207a213823975540c78d93a6be838/decode/index.js#L19

```js
[110,120,130,140].includes(v.time)  // 就是跳过时间为 110,120,130,140的消息
```

**Comment by hitech-h** [comment]
> [110,120,130,140].includes(v.time)  // 就是跳过时间为 110,120,130,140的消息

好像这样子是**只执行时间为 110,120,130,140的消息**
后面查了一下资料，反选应该是 `// rawMsgArr = _rawMsgArr.filter(v => ![1683792639].includes(v.time)); `

>这条的进度是 4811
进度条是处理一条更新一条

可能你没有理解“**因为解码时进度条大约每半秒才更新一次**”
我按照[你的方法](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/issues/9#issuecomment-1649125942)添加了很多时间，不过每次执行时都还是不同的结果

`rawMsgArr = _rawMsgArr.filter(v => ![1604837267,1620051197,1620534881,1620534846,1620050874,1620129882,1620051270,1620051267,1620051244,1620050874,1620050874].includes(v.time));`

于是还是觉得“**4811**”并不是真正报错的项
可能不太形象，我录制了一个视频，待会儿发到你邮箱

**Comment by lqzhgood** [comment]
那你在这里

https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/blob/0cb430a23f8f056928ca878eb4e5bdc68bd495fa/decode/index.js#L26

前面加一条 `console.log(i)`;  会打出每一条待处理的编号。

**Comment by hitech-h** [comment]
已解决，实际上出错的项为**4849**

```
4847
4848
4849
D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377
            throw Error("invalid wire type " + wireType + " at offset " + this.pos);
                  ^
```
**4849**我整理一下再上传
（最新的`decode/typeHandle/mixMsg.js`已解决`❌ mixMsg unknown type`类型的报错）
感谢

**Comment by lqzhgood** [comment]
> 已解决，实际上出错的项为**4849**
> 
> ```
> 4847
> 4848
> 4849
> D:\Shmily\Shmily-Get-MobileQQ-Andriod-main\node_modules\protobufjs\src\reader.js:377
>             throw Error("invalid wire type " + wireType + " at offset " + this.pos);
>                   ^
> ```
> 
> **4849**我整理一下再上传 （最新的`decode/typeHandle/mixMsg.js`已解决`❌ mixMsg unknown type`类型的报错） 感谢

mixMsg -> [🦄 refactor(mixMsg): 未知的混合类型消息不再抛出异常中断程序](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/commit/372d8462760518f2a2db771e1a51906089d8654f)

// mixMsg 类型 msgtype ==  -1035
只是不中断程序了，还是没解密，会输出在 `UNKNOWN_TYPE_PLEASE_ISSUES\1035-xxxxx.json`
